### ISSUE TITLE
The application doesn't have access to the library

### ISSUE THREAD

**Issue by prem96P** [LucJosin/on_audio_query#148]
D/CompatibilityChangeReporter(24897): Compat change id reported: 78294732; UID 10344; state: ENABLED
W/OnAudioQueryPlugin(24897): The application doesn't have access to the library
I/Quality (24897): Skipped: false 1 cost 25.091215 refreshRate 16735676 bit true processName com.example.ftp
E/AndroidRuntime(24897): FATAL EXCEPTION: main
E/AndroidRuntime(24897): Process: com.example.ftp, PID: 24897
E/AndroidRuntime(24897): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(24897): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:432)
E/AndroidRuntime(24897): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:266)
E/AndroidRuntime(24897): 	at com.lucasjosino.on_audio_query.queries.AudioQuery$querySongs$1.invokeSuspend(AudioQuery.kt:67)
E/AndroidRuntime(24897): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/AndroidRuntime(24897): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
E/AndroidRuntime(24897): 	at android.os.Handler.handleCallback(Handler.java:942)
E/AndroidRuntime(24897): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(24897): 	at android.os.Looper.loopOnce(Looper.java:240)
E/AndroidRuntime(24897): 	at android.os.Looper.loop(Looper.java:351)
E/AndroidRuntime(24897): 	at android.app.ActivityThread.main(ActivityThread.java:8370)
E/AndroidRuntime(24897): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(24897): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:568)
E/AndroidRuntime(24897): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
E/AndroidRuntime(24897): 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@fee4613, Dispatchers.Main.immediate]
I/Process (24897): Sending signal. PID: 24897 SIG: 9
Lost connection to device.

**Comment by rahul-mobilecoderz** [comment]
Any solutions
